In [3]:
pip install pandas

Requirement already satisfied: pandas in s:\AIML Courses\venv\Lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in s:\AIML Courses\venv\Lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in s:\AIML Courses\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in s:\AIML Courses\venv\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in s:\AIML Courses\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
data = [1,2,3,4,5]
data1 = (1,2,3,4,5,6)
s = pd.Series(data)
s1 = pd.Series(data1)
print(s)
print(s1)
print(type(s))
print(type(s1))

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.Series'>
<class 'pandas.Series'>

In [5]:
data = {"Sanjeev" : 21, "Eev" : 24, "Jeev" : 35}
s = pd.Series(data)
print(s)

Sanjeev    21
Eev        24
Jeev       35
dtype: int64

In [6]:
data = [10,20,30]
i = ['x','y','z']
s = pd.Series(data,index = i)
print(s)

x    10
y    20
z    30
dtype: int64

In [7]:
data = {
    "Name" : ["Krish", "John", "Jack"],
    "Age" : [25,32,42],
    "City" : ["Banglore","New York","Chennai"]
}
df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      City
0  Krish   25  Banglore
1   John   32  New York
2   Jack   42   Chennai
<class 'pandas.DataFrame'>

In [8]:
data = [
    {"Name": "Krish", "Age": 32, "City": "Bangalore"},
    {"Name": "John",  "Age": 34, "City": "Hongkon"},
    {"Name": "Jack",  "Age": 40, "City": "Chennai"}
]

df = pd.DataFrame(data)
print(df)
print(df.shape)
df.columns

    Name  Age       City
0  Krish   32  Bangalore
1   John   34    Hongkon
2   Jack   40    Chennai
(3, 3)

Index(['Name', 'Age', 'City'], dtype='str')

In [9]:
df.describe()

             Age
count   3.000000
mean   35.333333
std     4.163332
min    32.000000
25%    33.000000
50%    34.000000
75%    37.000000
max    40.000000

In [10]:
df.to_numpy()

array([['Krish', 32, 'Bangalore'],
       ['John', 34, 'Hongkon'],
       ['Jack', 40, 'Chennai']], dtype=object)

In [11]:
import numpy as np
s = np.array(df)
print(s)

[['Krish' 32 'Bangalore']
 ['John' 34 'Hongkon']
 ['Jack' 40 'Chennai']]

In [12]:
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34    Hongkon
2   Jack   40    Chennai

In [13]:
df['Name']

0    Krish
1     John
2     Jack
Name: Name, dtype: str

In [14]:
df['Age']

0    32
1    34
2    40
Name: Age, dtype: int64

In [15]:
df['City']

0    Bangalore
1      Hongkon
2      Chennai
Name: City, dtype: str

In [16]:

df.loc[2]

Name       Jack
Age          40
City    Chennai
Name: 2, dtype: object

In [17]:
df.loc[1]

Name       John
Age          34
City    Hongkon
Name: 1, dtype: object

In [18]:
print(df.loc[1])
print(df.loc[2])
print(df.loc[0])

Name       John
Age          34
City    Hongkon
Name: 1, dtype: object
Name       Jack
Age          40
City    Chennai
Name: 2, dtype: object
Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In [19]:
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34    Hongkon
2   Jack   40    Chennai

In [20]:
df.iloc[0]

Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In [21]:
df.loc[1]

Name       John
Age          34
City    Hongkon
Name: 1, dtype: object

In [22]:
df.iloc[1]

Name       John
Age          34
City    Hongkon
Name: 1, dtype: object

In [23]:
df.at[1,"Age"]

np.int64(34)

In [24]:
print(df.at[1,"Age"])

34

In [25]:
df.iat[1,1]

np.int64(34)

In [26]:
print(df.iat[1,1])

34

In [27]:
df["Salary"] = [5000,1000,19919]
df

    Name  Age       City  Salary
0  Krish   32  Bangalore    5000
1   John   34    Hongkon    1000
2   Jack   40    Chennai   19919

In [28]:
df.drop("Salary",axis = 1)

    Name  Age       City
0  Krish   32  Bangalore
1   John   34    Hongkon
2   Jack   40    Chennai

In [29]:
df

    Name  Age       City  Salary
0  Krish   32  Bangalore    5000
1   John   34    Hongkon    1000
2   Jack   40    Chennai   19919

In [30]:
df.drop("Salary", axis = 1, inplace = True)

In [31]:
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34    Hongkon
2   Jack   40    Chennai

In [32]:
df.drop(0,inplace = True)

In [33]:
df

   Name  Age     City
1  John   34  Hongkon
2  Jack   40  Chennai

In [34]:
df.shape

(2, 3)

In [35]:
df.columns

Index(['Name', 'Age', 'City'], dtype='str')

In [36]:
df.dtypes

Name      str
Age     int64
City      str
dtype: object

In [37]:
df.isnull()

    Name    Age   City
1  False  False  False
2  False  False  False

In [38]:
df.isnull().sum()

Name    0
Age     0
City    0
dtype: int64

In [39]:
df_filled = df.fillna(0)

In [40]:
df

   Name  Age     City
1  John   34  Hongkon
2  Jack   40  Chennai

In [41]:
df["AvgAge"] = df["Age"].fillna(df["Age"].mean())

In [42]:
df

   Name  Age     City  AvgAge
1  John   34  Hongkon      34
2  Jack   40  Chennai      40

In [43]:
df.drop("AvgAge", axis = 1)

   Name  Age     City
1  John   34  Hongkon
2  Jack   40  Chennai

In [44]:
df

   Name  Age     City  AvgAge
1  John   34  Hongkon      34
2  Jack   40  Chennai      40

In [45]:
df.drop("AvgAge", axis = 1,inplace = True)

In [46]:
df

   Name  Age     City
1  John   34  Hongkon
2  Jack   40  Chennai

In [47]:
df.rename(columns = {"Age" : "Person_Age"}, inplace = True)

In [48]:
df

   Name  Person_Age     City
1  John          34  Hongkon
2  Jack          40  Chennai

In [49]:
df["Age_Inc"] = df["Person_Age"].apply(lambda x: x + 2 if pd.notnull(x) else x)

In [50]:
df

   Name  Person_Age     City  Age_Inc
1  John          34  Hongkon       36
2  Jack          40  Chennai       42

In [51]:
import pandas as pd
from io import StringIO

json_data = """
{
  "employee_name": "James",
  "email": "james@gmail.com",
  "job_profile": [
    {"title1": "Team Lead"},
    {"title2": "Senior Developer"}
  ]
}
"""

In [52]:
df = pd.read_json(StringIO(json_data))
df

  employee_name            email                     job_profile
0         James  james@gmail.com         {'title1': 'Team Lead'}
1         James  james@gmail.com  {'title2': 'Senior Developer'}

In [57]:
df.to_json(orient= "records")
# print(df)

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead"}},{"employee_name":"James","email":"james@gmail.com","job_profile":{"title2":"Senior Developer"}}]'

In [59]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data"
df = pd.read_csv(url,header=None)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [60]:
df.to_csv("wine.csv",index=False)

In [62]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.0.2-cp313-cp313-win_amd64.whl.metadata (3.7 kB)
Downloading lxml-6.0.2-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 633.8 kB/s eta 0:00:06
   ----- ---------------------------------- 0.5/4.0 MB 633.8 kB/s eta 0:00:06
   ------- -------------------------------- 0.8/4.0 MB 705.4 kB/s eta 0:00:05
   ------- -------------------------------- 0.8/4.0 MB 705.4 kB/s eta 0:00:05
   ---------- ----------------------------- 1.0/4.0 MB 677.1 kB/s eta 0:00:05
   ---------- ----------------------------- 1.0/4.0 MB 677.1 kB/s eta 0:00:05
   ------------- -------------------------- 1.3/4.0 MB 701.0 kB/s eta 0:00:04
   --------------- ------------------------ 1.6/4.0 MB 711.0 kB/s eta 0:00:04
   --------------- ------------------------ 1.6/4.0 MB 711.0 kB/s eta 0:00:04
   ------------------ --------------------- 1.8/4.0 MB 696.5 kB/s eta 0:00:04
   -------------------- ------------------- 2.1/4.0 MB 737.4 kB/s eta 0:00:03
   ----------------------- ---------------- 2.4/4.0 MB 772.7 kB/s eta 0:00:03
   ----------------------- ---------------- 2.4/4.0 MB 772.7 kB/s eta 0:00:03
   ---------------------------- ----------- 2.9/4.0 MB 828.2 kB/s eta 0:00:02
   ------------------------------- -------- 3.1/4.0 MB 854.1 kB/s eta 0:00:02
   --------------------------------- ------ 3.4/4.0 MB 886.5 kB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 902.2 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 923.2 kB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 918.4 kB/s  0:00:04
Installing collected packages: lxml
Successfully installed lxml-6.0.2

In [65]:
pip install lxml html5lib beautifulsoup4

Requirement already satisfied: lxml in s:\AIML Courses\venv\Lib\site-packages (6.0.2)
Collecting html5lib
  Downloading html5lib-1.1-py2.py3-none-any.whl.metadata (16 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: six>=1.9 in s:\AIML Courses\venv\Lib\site-packages (from html5lib) (1.17.0)
Collecting webencodings (from html5lib)
  Downloading webencodings-0.5.1-py2.py3-none-any.whl.metadata (2.1 kB)
Collecting soupsieve>=1.6.1 (from beautifulsoup4)
  Downloading soupsieve-2.8.3-py3-none-any.whl.metadata (4.6 kB)
Collecting typing-extensions>=4.0.0 (from beautifulsoup4)
  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
Downloading soupsieve-2.8.3-py3-none-any.whl (37 kB)
Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Installing collected packages: webencodings, typing-extensions, soupsieve, html5lib, beautifulsoup4

   -------- ------------------------------- 1/5 [typing-extensions]
   ------------------------ --------------- 3/5 [html5lib]
   ------------------------ --------------- 3/5 [html5lib]
   -------------------------------- ------- 4/5 [beautifulsoup4]
   ---------------------------------------- 5/5 [beautifulsoup4]

Successfully installed beautifulsoup4-4.14.3 html5lib-1.1 soupsieve-2.8.3 typing-extensions-4.15.0 webencodings-0.5.1
Note: you may need to restart the kernel to use updated packages.

In [67]:
pip install requests

Collecting requests
  Downloading requests-2.32.5-py3-none-any.whl.metadata (4.9 kB)
Collecting charset_normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.4.4-cp313-cp313-win_amd64.whl.metadata (38 kB)
Collecting idna<4,>=2.5 (from requests)
  Using cached idna-3.11-py3-none-any.whl.metadata (8.4 kB)
Collecting urllib3<3,>=1.21.1 (from requests)
  Downloading urllib3-2.6.3-py3-none-any.whl.metadata (6.9 kB)
Collecting certifi>=2017.4.17 (from requests)
  Using cached certifi-2026.1.4-py3-none-any.whl.metadata (2.5 kB)
Downloading requests-2.32.5-py3-none-any.whl (64 kB)
Downloading charset_normalizer-3.4.4-cp313-cp313-win_amd64.whl (107 kB)
Using cached idna-3.11-py3-none-any.whl (71 kB)
Downloading urllib3-2.6.3-py3-none-any.whl (131 kB)
Using cached certifi-2026.1.4-py3-none-any.whl (152 kB)
Installing collected packages: urllib3, idna, charset_normalizer, certifi, requests

   -------- ------------------------------- 1/5 [idna]
   ---------------------------------------- 5/5 [requests]

Successfully installed certifi-2026.1.4 charset_normalizer-3.4.4 idna-3.11 requests-2.32.5 urllib3-2.6.3
Note: you may need to restart the kernel to use updated packages.

In [72]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [76]:
import pandas as pd
import requests
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)
response.raise_for_status()   # ensures request succeeded

# Convert HTML string to file-like object
html_data = StringIO(response.text)

tables = pd.read_html(html_data)

print("Number of tables:", len(tables))
print(tables[0].head())

Number of tables: 5
  ISO 3166[1] name[5] Sovereignty [6][7][8] ISO 3166-1[2]                   \
  ISO 3166[1] name[5] Sovereignty [6][7][8]       A-2 [5] A-3 [5] Num. [5]
0                 NaN                   NaN           NaN     NaN      NaN
1         Afghanistan             UN member            AF     AFG      004
2       Åland Islands               Finland            AX     ALA      248
3             Albania             UN member            AL     ALB      008
4             Algeria             UN member            DZ     DZA      012

  ISO 3166-2[3] subdivision codes link TLD [9]
  ISO 3166-2[3] subdivision codes link TLD [9]
0                                  NaN     NaN
1                        ISO 3166-2:AF     .af
2                        ISO 3166-2:AX     .ax
3                        ISO 3166-2:AL     .al
4                        ISO 3166-2:DZ     .dz

In [78]:
df = pd.read_excel("data.xlsx", sheet_name=0)
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'data.xlsx'